### ISSUE TITLE
Needed the config and dotfiles on Arch Install

### ISSUE THREAD

**Issue by Coder684** [archcraft-os/archcraft-pkgs#2]
# DOTFILES NEEDED

I have a minimal arch install. I love the default config and theme of ArchCraft. I wanted the same on my installation without leaving my Arch Installation. So I wanted to recreate the same environment on my Arch Installation. Could you please share the dotfiles?

**Comment by adi1090x** [comment]
Here : https://github.com/archcraft-os/archcraft-style-openbox
